### ISSUE TITLE
SAP Type of a CMAF segment with MP4 Audio, and 1 or more priming samples, the track carrying an edit list to remove the priming samples from the presentation timeline

### ISSUE THREAD

**Issue by RufaelDev** [MPEGGroup/CMAF#25]
It would be good to clarify the SAP type of a MP4 audio segment in case the CMAF track contains an edit list that is used to remove 1 or more ISO-BMFF samples enclosed in the segment from the presentation timeline. 

It is always assumed and mentioned that SAP type is 1, but there is room for different interpretations as the presentation time of samples not rendered is negative or undefined.

**Comment by cconcolato** [comment]
The fact that a sample is edited-out does not affect its SAP type.

**Comment by RufaelDev** [comment]
According to 14496-12 annex I sap types are based on presentation times that are changed by the edit, also in this case the definition of "correctly decoded" can be interpreted in different ways, so some additional explanation may still be helpful

**Comment by dwsinger** [comment]
we treat AAC as being all SAP type 1, though logically the 'roll' sample group (which ought to be mapped to all samples) makes it all SAP type 4. At the beginning of a segment, you might like to pre-roll, but you can't. We do not copy audio frames from the end of a segment to enable pre-roll of segments, because it would confuse, and we don't support edit lists in segments, which is what we'd need to remove them.

**Comment by RufaelDev** [comment]
this all makes sense, is there a need to add some text in the audio track section on this or is having this issue as a reference for interpreting the specification sufficient ?

**Comment by cconcolato** [comment]
In practice, the group believes it is fine to use SAP type 1 as indicated here, and concrete examples of problems (if any) are welcome. We welcome proposals to clearly document the impact of this approach.
