### ISSUE TITLE
Constraint on conformance cropping window offsets in VVC Media Profile

### ISSUE THREAD

**Issue by vdrugeon** [MPEGGroup/CMAF#39]
The current VVC CMAF Media Profile draft contains the following constraint: "SPS and PPS cropping parameters sps_conf_win_top_offset / pps_conf_win_top_offset and sps_conf_win_left_offset / pps_conf_win_left_offset shall be set to 0."

The conformance cropping window is something internal to the coding standard that has to be supported by all conforming VVC decoders. The systems layer will only ever see the decoder output, which will always be the cropped image. So why is this constraint necessary for CMAF? Is there not a risk to make CMAF less general?

**Comment by krasimirkolarov** [comment]
The group looked at this at the second AdHoc meeting on March 14, 2022. There is an agreement to implement in the FDIS specification. If you disagree, please comment here before the next meeting in April.

**Comment by vdrugeon** [comment]
As mentioned during the AHG call, there may be a need for a constraint for these offsets not to change within a switching set. However such a constraint would then apply to all the conformance window offsets, including the ones at the right and bottom of the picture.

**Comment by yekuiwang** [comment]
I support to drop the constraint. The benefit of dropping it is that that would support some concrete use case. The potential disadvantage is that dropping it would make VVC different in this aspect compared to HEVC. However, unless there was an important reason to have such a constraint, since there are VVC aspects that are different than HEVC anyway, I think dropping to support a use case wins here over just having one more small aspect aligned between VVC and HEVC in the CMAF specification.

**Comment by haudiobe** [comment]
BOG AF MPEG#139

addressed in 3rd edition

close the issue
